version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Prepare commit metadata
          command: |
            mkdir -p /tmp/commit-metadata
            echo -n "$(date)" > /tmp/commit-metadata/lastBuilt
            echo -n '{"works":true}' > /tmp/commit-metadata/jsonInfo.json
            echo -n '{"works":true}' > /tmp/commit-metadata/nested.json.info.json
            echo -n '99' > /tmp/commit-metadata/hello.world
      - run:
          name: CLI
          command: yarn cli --commitMetadataPath=/tmp/commit-metadata --pullRequest=$CIRCLE_PULL_REQUEST
